services:
  - type: web
    name: mutantes-api
    env: java
    buildCommand: bash ./gradlew build -x test
    startCommand: java -jar build/libs/mutantes-api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: mutantes-db
          property: connectionString

databases:
  - name: mutantes-db
    databaseName: mutantes
    user: mutantes_user