services:
  - type: web
    name: mutantes-api
    env: java
    plan: free
    buildCommand: ./gradlew clean build -x test
    startCommand: java -jar build/libs/mutantes-api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mutantes-db
          property: connectionString