services:
  - type: web
    name: mutantes-api
    env: java
    plan: free
    buildCommand: chmod +x gradlew && ./gradlew build
    startCommand: java -jar build/libs/mutantes-api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mutantes-db
          property: connectionString

databases:
  - name: mutantes-db
    databaseName: mutantes